stages:
  - deploy

test_runner:
  stage: test
  only:
    - feature/not_queue
  tags:
    - ec2   # trùng với tag bạn đăng ký runner
  script:
    - echo "✅ Runner trên EC2 đã hoạt động!"
    - uname -a
    - whoami
